export default {
  signUp: 'Kayıt Ol',
  signIn: 'Giriş Yap',
  email: 'E-posta',
  password: 'Parola',
  passwordAgain: 'Parola Tekrar',
  passwordsNotSame: 'Parolalar Aynı Değil!',
  invalidEmail: 'E-posta Adresiniz Yanlış Formattadır!',
  successSignUp: 'Üye işlemi başarılı',
  weakPassword: 'Daha Güçlü Bir Parola Giriniz!',
  emailAlreadyInUse: 'Bu E-posta Adresi Zaten Kullanılıyor!',
  userNotFound: 'Kullanıcı Bulunamadı!',
  wrongPassword: 'Yanlış Parola Girdiniz!',
  addBtnText: 'Mesaj Ekle',
  addTxtPlaceholder: 'Mesajınız...',
  send: 'Gönder',
  addRoom: 'Oda Ekle',
  addRoomPlaceHolder: 'Oda İsmi...',
  rooms: 'Odalar',
};
